// Auto-generated by sync_garmin.py on 2026-04-24 08:57:12
// This file is loaded by dashboard.html to update run data
const syncedRunData = [
  {
    "id": "22628986901",
    "name": "Novara Running",
    "date": "2026-04-23",
    "distance": 13.52,
    "duration": "1:15:19",
    "pace": "5:34",
    "avgHr": 151.0,
    "maxHr": 159.0,
    "cadence": 162.796875,
    "calories": 973.0,
    "aerobic": 4.599999904632568,
    "anaerobic": 0,
    "power": 313.0,
    "elevation": 86,
    "splits": [
      {
        "km": 1,
        "pace": "5:31",
        "hr": 134.0,
        "cad": 166.96875,
        "elev": 5,
        "power": 316.0
      },
      {
        "km": 2,
        "pace": "5:30",
        "hr": 146.0,
        "cad": 163.609375,
        "elev": 0,
        "power": 311.0
      },
      {
        "km": 3,
        "pace": "5:28",
        "hr": 147.0,
        "cad": 161.90625,
        "elev": 4,
        "power": 324.0
      },
      {
        "km": 4,
        "pace": "5:31",
        "hr": 148.0,
        "cad": 160.375,
        "elev": 0,
        "power": 316.0
      },
      {
        "km": 5,
        "pace": "5:27",
        "hr": 150.0,
        "cad": 159.703125,
        "elev": 0,
        "power": 306.0
      },
      {
        "km": 6,
        "pace": "5:33",
        "hr": 151.0,
        "cad": 160.1875,
        "elev": 3,
        "power": 312.0
      },
      {
        "km": 7,
        "pace": "5:34",
        "hr": 153.0,
        "cad": 159.15625,
        "elev": 5,
        "power": 320.0
      },
      {
        "km": 8,
        "pace": "5:38",
        "hr": 153.0,
        "cad": 160.671875,
        "elev": 15,
        "power": 329.0
      },
      {
        "km": 9,
        "pace": "5:32",
        "hr": 155.0,
        "cad": 161.375,
        "elev": 8,
        "power": 314.0
      },
      {
        "km": 10,
        "pace": "5:35",
        "hr": 156.0,
        "cad": 162.9375,
        "elev": 11,
        "power": 316.0
      },
      {
        "km": 11,
        "pace": "5:39",
        "hr": 155.0,
        "cad": 164.359375,
        "elev": 6,
        "power": 299.0
      },
      {
        "km": 12,
        "pace": "5:37",
        "hr": 155.0,
        "cad": 165.375,
        "elev": 16,
        "power": 314.0
      },
      {
        "km": 13,
        "pace": "5:42",
        "hr": 155.0,
        "cad": 166.71875,
        "elev": 10,
        "power": 303.0
      },
      {
        "km": 14,
        "pace": "5:37",
        "hr": 154.0,
        "cad": 167.96875,
        "elev": 3,
        "power": 300.0
      }
    ],
    "hrZones": [
      {
        "zone": "Z1",
        "pct": 0
      },
      {
        "zone": "Z2",
        "pct": 2
      },
      {
        "zone": "Z3",
        "pct": 57
      },
      {
        "zone": "Z4",
        "pct": 40
      },
      {
        "zone": "Z5",
        "pct": 0
      }
    ]
  },
  {
    "id": "22577824668",
    "name": "Novara Running",
    "date": "2026-04-19",
    "distance": 10.01,
    "duration": "54:42",
    "pace": "5:27",
    "avgHr": 146.0,
    "maxHr": 164.0,
    "cadence": 167.78125,
    "calories": 702.0,
    "aerobic": 4.099999904632568,
    "anaerobic": 0,
    "power": 309.0,
    "elevation": 35,
    "splits": [
      {
        "km": 1,
        "pace": "5:58",
        "hr": 128.0,
        "cad": 171.671875,
        "elev": 12,
        "power": 288.0
      },
      {
        "km": 2,
        "pace": "5:39",
        "hr": 139.0,
        "cad": 172.796875,
        "elev": 1,
        "power": 283.0
      },
      {
        "km": 3,
        "pace": "5:30",
        "hr": 144.0,
        "cad": 168.921875,
        "elev": 0,
        "power": 302.0
      },
      {
        "km": 4,
        "pace": "5:30",
        "hr": 146.0,
        "cad": 167.03125,
        "elev": 0,
        "power": 300.0
      },
      {
        "km": 5,
        "pace": "5:31",
        "hr": 148.0,
        "cad": 167.921875,
        "elev": 5,
        "power": 311.0
      },
      {
        "km": 6,
        "pace": "5:32",
        "hr": 148.0,
        "cad": 166.203125,
        "elev": 1,
        "power": 310.0
      },
      {
        "km": 7,
        "pace": "5:23",
        "hr": 151.0,
        "cad": 165.625,
        "elev": 5,
        "power": 323.0
      },
      {
        "km": 8,
        "pace": "5:19",
        "hr": 151.0,
        "cad": 165.25,
        "elev": 1,
        "power": 320.0
      },
      {
        "km": 9,
        "pace": "5:19",
        "hr": 152.0,
        "cad": 166.03125,
        "elev": 2,
        "power": 319.0
      },
      {
        "km": 10,
        "pace": "4:55",
        "hr": 158.0,
        "cad": 165.484375,
        "elev": 7,
        "power": 345.0
      },
      {
        "km": 11,
        "pace": "5:15",
        "hr": 156.0,
        "cad": 164.328125,
        "elev": 0,
        "power": 320.0
      }
    ],
    "hrZones": [
      {
        "zone": "Z1",
        "pct": 1
      },
      {
        "zone": "Z2",
        "pct": 19
      },
      {
        "zone": "Z3",
        "pct": 70
      },
      {
        "zone": "Z4",
        "pct": 9
      },
      {
        "zone": "Z5",
        "pct": 0
      }
    ]
  },
  {
    "id": "22551058713",
    "name": "Novara Running",
    "date": "2026-04-16",
    "distance": 7.03,
    "duration": "43:03",
    "pace": "6:07",
    "avgHr": 135.0,
    "maxHr": 144.0,
    "cadence": 162.78125,
    "calories": 497.0,
    "aerobic": 3.0999999046325684,
    "anaerobic": 0,
    "power": 288.0,
    "elevation": 17,
    "splits": [
      {
        "km": 1,
        "pace": "6:05",
        "hr": 122.0,
        "cad": 163.5625,
        "elev": 3,
        "power": 291.0
      },
      {
        "km": 2,
        "pace": "5:57",
        "hr": 133.0,
        "cad": 161.5,
        "elev": 0,
        "power": 296.0
      },
      {
        "km": 3,
        "pace": "6:02",
        "hr": 136.0,
        "cad": 160.984375,
        "elev": 1,
        "power": 291.0
      },
      {
        "km": 4,
        "pace": "6:13",
        "hr": 139.0,
        "cad": 161.671875,
        "elev": 2,
        "power": 288.0
      },
      {
        "km": 5,
        "pace": "6:09",
        "hr": 139.0,
        "cad": 163.265625,
        "elev": 5,
        "power": 287.0
      },
      {
        "km": 6,
        "pace": "6:17",
        "hr": 139.0,
        "cad": 163.8125,
        "elev": 4,
        "power": 286.0
      },
      {
        "km": 7,
        "pace": "6:08",
        "hr": 140.0,
        "cad": 164.625,
        "elev": 1,
        "power": 276.0
      },
      {
        "km": 8,
        "pace": "5:39",
        "hr": 138.0,
        "cad": 163.5,
        "elev": 0,
        "power": 260.0
      }
    ],
    "hrZones": [
      {
        "zone": "Z1",
        "pct": 7
      },
      {
        "zone": "Z2",
        "pct": 83
      },
      {
        "zone": "Z3",
        "pct": 10
      },
      {
        "zone": "Z4",
        "pct": 0
      },
      {
        "zone": "Z5",
        "pct": 0
      }
    ]
  },
  {
    "id": "22498821952",
    "name": "Milan Marathon 2026",
    "date": "2026-04-12",
    "distance": 42.73,
    "duration": "4:05:22",
    "pace": "5:44",
    "avgHr": 151.0,
    "maxHr": 165.0,
    "cadence": 167.3125,
    "calories": 3061.0,
    "aerobic": 5.0,
    "anaerobic": 0,
    "power": 298.0,
    "elevation": 153
  },
  {
    "id": "22483976818",
    "name": "Novara - Shake Out Run - MM",
    "date": "2026-04-11",
    "distance": 3.35,
    "duration": "21:26",
    "pace": "6:24",
    "avgHr": 136.0,
    "maxHr": 148.0,
    "cadence": 162.703125,
    "calories": 246.0,
    "aerobic": 2.5,
    "anaerobic": 0.5,
    "power": 275.0,
    "elevation": 28
  },
  {
    "id": "22422824982",
    "name": "Novara - Run Fartlek easy",
    "date": "2026-04-06",
    "distance": 8.54,
    "duration": "50:01",
    "pace": "5:51",
    "avgHr": 139.0,
    "maxHr": 156.0,
    "cadence": 165.6875,
    "calories": 608.0,
    "aerobic": 3.4000000953674316,
    "anaerobic": 0.20000000298023224,
    "power": 295.0,
    "elevation": 34
  },
  {
    "id": "22400761901",
    "name": "Novara - Run Workout 15km",
    "date": "2026-04-04",
    "distance": 15.52,
    "duration": "1:26:17",
    "pace": "5:33",
    "avgHr": 143.0,
    "maxHr": 152.0,
    "cadence": 165.234375,
    "calories": 1077.0,
    "aerobic": 4.400000095367432,
    "anaerobic": 0.10000000149011612,
    "power": 309.0,
    "elevation": 49
  },
  {
    "id": "22378655394",
    "name": "Novara Running",
    "date": "2026-04-02",
    "distance": 10.13,
    "duration": "58:12",
    "pace": "5:44",
    "avgHr": 138.0,
    "maxHr": 149.0,
    "cadence": 176.765625,
    "calories": 718.0,
    "aerobic": 3.700000047683716,
    "anaerobic": 0,
    "power": 295.0,
    "elevation": 83
  },
  {
    "id": "22370797948",
    "name": "Novara - Run 4x1000m",
    "date": "2026-04-01",
    "distance": 8.47,
    "duration": "46:32",
    "pace": "5:29",
    "avgHr": 148.0,
    "maxHr": 163.0,
    "cadence": 159.109375,
    "calories": 606.0,
    "aerobic": 3.799999952316284,
    "anaerobic": 1.399999976158142,
    "power": 324.0,
    "elevation": 69
  },
  {
    "id": "22323708052",
    "name": "Novara - Run Workout Tapering 1",
    "date": "2026-03-28",
    "distance": 21.32,
    "duration": "1:56:17",
    "pace": "5:27",
    "avgHr": 145.0,
    "maxHr": 153.0,
    "cadence": 164.171875,
    "calories": 1476.0,
    "aerobic": 5.0,
    "anaerobic": 0.10000000149011612,
    "power": 317.0,
    "elevation": 125
  },
  {
    "id": "22291422730",
    "name": "Novara Running",
    "date": "2026-03-25",
    "distance": 10.02,
    "duration": "59:52",
    "pace": "5:58",
    "avgHr": 134.0,
    "maxHr": 143.0,
    "cadence": 173.109375,
    "calories": 708.0,
    "aerobic": 3.4000000953674316,
    "anaerobic": 0,
    "power": 285.0,
    "elevation": 57
  },
  {
    "id": "22270547273",
    "name": "Novara - Run Workout",
    "date": "2026-03-23",
    "distance": 11.72,
    "duration": "1:03:42",
    "pace": "5:26",
    "avgHr": 148.0,
    "maxHr": 162.0,
    "cadence": 161.40625,
    "calories": 821.0,
    "aerobic": 4.400000095367432,
    "anaerobic": 0.20000000298023224,
    "power": 315.0,
    "elevation": 59
  },
  {
    "id": "22245955900",
    "name": "Novara - Last Long Run - Road to MM",
    "date": "2026-03-21",
    "distance": 36.51,
    "duration": "3:27:36",
    "pace": "5:41",
    "avgHr": 145.0,
    "maxHr": 163.0,
    "cadence": 166.953125,
    "calories": 2526.0,
    "aerobic": 5.0,
    "anaerobic": 0,
    "power": 301.0,
    "elevation": 163
  }
];
const syncedMonthlyData = [
  {
    "month": "2025-04",
    "km": 37.1,
    "runs": 3
  },
  {
    "month": "2025-05",
    "km": 182.0,
    "runs": 17
  },
  {
    "month": "2025-06",
    "km": 175.4,
    "runs": 15
  },
  {
    "month": "2025-07",
    "km": 164.3,
    "runs": 14
  },
  {
    "month": "2025-08",
    "km": 188.5,
    "runs": 14
  },
  {
    "month": "2025-09",
    "km": 181.9,
    "runs": 15
  },
  {
    "month": "2025-10",
    "km": 210.7,
    "runs": 18
  },
  {
    "month": "2025-11",
    "km": 214.0,
    "runs": 15
  },
  {
    "month": "2025-12",
    "km": 203.1,
    "runs": 15
  },
  {
    "month": "2026-01",
    "km": 166.8,
    "runs": 12
  },
  {
    "month": "2026-02",
    "km": 226.6,
    "runs": 13
  },
  {
    "month": "2026-03",
    "km": 223.5,
    "runs": 12
  },
  {
    "month": "2026-04",
    "km": 119.3,
    "runs": 9
  }
];
const syncedAthleteProfile = {
  "lastUpdated": "2026-04-24",
  "vo2max": 48.5,
  "trainingLoad7Day": 853,
  "trainingLoad28Day": 881,
  "recoveryTime": 0,
  "trainingStatus": "Maintaining 2",
  "lactateThresholdHR": 159,
  "lactateThresholdPace": "49:10",
  "racePredictions": {
    "userId": 117552933,
    "fromCalendarDate": null,
    "toCalendarDate": null,
    "calendarDate": "2026-04-24",
    "time5K": 1312,
    "time10K": 2758,
    "timeHalfMarathon": 6108,
    "timeMarathon": 13421
  },
  "lactateThresholdPower": {
    "ftp": 345,
    "wpkg": 4.791666666666667
  }
};
const syncedVO2MaxTrend = [
  {
    "date": "2026-01-25",
    "vo2max": 50.2
  },
  {
    "date": "2026-01-29",
    "vo2max": 50.3
  },
  {
    "date": "2026-02-01",
    "vo2max": 50.2
  },
  {
    "date": "2026-02-05",
    "vo2max": 50.4
  },
  {
    "date": "2026-02-07",
    "vo2max": 50.1
  },
  {
    "date": "2026-02-10",
    "vo2max": 50.2
  },
  {
    "date": "2026-02-12",
    "vo2max": 50.4
  },
  {
    "date": "2026-02-14",
    "vo2max": 50.2
  },
  {
    "date": "2026-02-16",
    "vo2max": 50.3
  },
  {
    "date": "2026-02-21",
    "vo2max": 50.1
  },
  {
    "date": "2026-02-23",
    "vo2max": 50.0
  },
  {
    "date": "2026-02-26",
    "vo2max": 50.3
  },
  {
    "date": "2026-02-28",
    "vo2max": 50.2
  },
  {
    "date": "2026-03-02",
    "vo2max": 50.0
  },
  {
    "date": "2026-03-07",
    "vo2max": 49.6
  },
  {
    "date": "2026-03-09",
    "vo2max": 49.5
  },
  {
    "date": "2026-03-12",
    "vo2max": 49.4
  },
  {
    "date": "2026-03-14",
    "vo2max": 49.3
  },
  {
    "date": "2026-03-16",
    "vo2max": 49.2
  },
  {
    "date": "2026-03-19",
    "vo2max": 49.4
  },
  {
    "date": "2026-03-21",
    "vo2max": 49.3
  },
  {
    "date": "2026-04-02",
    "vo2max": 49.5
  },
  {
    "date": "2026-04-04",
    "vo2max": 49.4
  },
  {
    "date": "2026-04-06",
    "vo2max": 49.5
  },
  {
    "date": "2026-04-11",
    "vo2max": 49.4
  },
  {
    "date": "2026-04-12",
    "vo2max": 48.8
  },
  {
    "date": "2026-04-19",
    "vo2max": 48.7
  },
  {
    "date": "2026-04-23",
    "vo2max": 48.5
  }
];

// Override data with synced data if available
if (typeof syncedRunData !== 'undefined' && syncedRunData.length > 0) {
  recentRuns.length = 0;
  syncedRunData.forEach(r => recentRuns.push(r));
}
if (typeof syncedMonthlyData !== 'undefined' && syncedMonthlyData.length > 0) {
  monthlyVolume.length = 0;
  syncedMonthlyData.forEach(m => monthlyVolume.push(m));
}
if (typeof syncedAthleteProfile !== 'undefined') {
  window.athleteProfile = syncedAthleteProfile;
}
if (typeof syncedVO2MaxTrend !== 'undefined' && syncedVO2MaxTrend.length > 0) {
  window.vo2maxTrend = syncedVO2MaxTrend;
}
console.log('Synced data loaded: ' + recentRuns.length + ' runs, ' + monthlyVolume.length + ' months, athlete profile, ' + (syncedVO2MaxTrend?.length || 0) + ' VO2max data points');
